"""Remove profile picture and add primary saving goal

Revision ID: ea28269e63b5
Revises: 6dee1339c39e
Create Date: 2025-05-12 12:11:41.774010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea28269e63b5'
down_revision = '6dee1339c39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_saving_goal', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('primary_saving_goal')

    with op.batch_alter_table('shared_expense', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
